// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OnlineCVAPI.Models;
using System;

namespace OnlineCVAPI.Migrations
{
    [DbContext(typeof(OnlineCVDBContext))]
    [Migration("20180111223722_InitializeDB")]
    partial class InitializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineCVAPI.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("creationDateTime");

                    b.Property<int>("profileId");

                    b.Property<int>("templateId");

                    b.HasKey("Id");

                    b.HasIndex("profileId");

                    b.HasIndex("templateId");

                    b.ToTable("CV");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.CVTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("templateHtmlFile");

                    b.Property<string>("templateImageFile");

                    b.Property<string>("templateName");

                    b.HasKey("Id");

                    b.ToTable("CVTemplate");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Education", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CVId");

                    b.Property<string>("graduationYear");

                    b.Property<string>("institute");

                    b.HasKey("ID");

                    b.HasIndex("CVId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CVId");

                    b.Property<string>("Employer");

                    b.Property<string>("Location");

                    b.Property<string>("endMonth");

                    b.Property<string>("endYear");

                    b.Property<string>("jobTitle");

                    b.Property<string>("startMonth");

                    b.Property<string>("startYear");

                    b.Property<int>("stillInRole");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("WorkHistory");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.PersonalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("phoneNumber");

                    b.HasKey("Id");

                    b.ToTable("PersonalProfile");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CVId");

                    b.Property<string>("Institute");

                    b.Property<string>("skillName");

                    b.Property<string>("year");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("SkillAndCertificate");
                });

            modelBuilder.Entity("OnlineCVAPI.Models.CV", b =>
                {
                    b.HasOne("OnlineCVAPI.Models.PersonalProfile", "profile")
                        .WithMany("CVs")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineCVAPI.Models.CVTemplate", "template")
                        .WithMany("CVs")
                        .HasForeignKey("templateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Education", b =>
                {
                    b.HasOne("OnlineCVAPI.Models.CV", "cv")
                        .WithMany("Educations")
                        .HasForeignKey("CVId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Experience", b =>
                {
                    b.HasOne("OnlineCVAPI.Models.CV", "cv")
                        .WithMany("Experiences")
                        .HasForeignKey("CVId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineCVAPI.Models.Skill", b =>
                {
                    b.HasOne("OnlineCVAPI.Models.CV", "cv")
                        .WithMany("Skills")
                        .HasForeignKey("CVId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
